const ingredients = [
  {id: "red_meat", "type": "Main", "label": "🥩 Red Meat"},
  {id: "pork", "type": "Main", "label": "🐷 Pork"},
  {id: "poultry", "type": "Main", "label": "🍗 Poultry"},
  {id: "cured_meat", "type": "Main", "label": "🥓 Ham/Bacon"},
  {id: "fish", "type": "Main", "label": "🐟 Fish"},
  {id: "lobster", "type": "Main", "label": "🍤 Shellfish/Lobster"},
  {id: "mollusks", "type": "Main", "label": "🦪 Oysters/Mussels/Clams"},
  {id: "soft_cheese", "type": "Main", "label": "🥯 Soft Cheese"},
  {id: "pungent_cheese", "type": "Main", "label": "😱 Smelly Cheese"},
  {id: "hard_cheese", "type": "Main", "label": "🧀 Hard Cheese"},
  {id: "fruits", "type": "Main", "label": "🍎 Fruits/Berries"},
  {id: "vanilla", "type": "Main", "label": "🍨 Vanilla/Caramel"},
  {id: "chocolate", "type": "Main", "label": "🍫 Chocolate/Coffee"},
  
  {id: "white_starches", "type": "Secondary", "label": "🍝 Pasta/Rice/Bread"},
  {id: "potato", "type": "Secondary", "label": "🥔 Potatoes"},
  {id: "green_veg", "type": "Secondary", "label": "🥦 Green Veggies"},
  {id: "root_veg", "type": "Secondary", "label": "🎃 Pumpkin/Carrot"},
  {id: "nightshades", "type": "Secondary", "label": "🍅 Tomato/Bell Pepper/Eggplant"},
  {id: "mushrooms", "type": "Secondary", "label": "🍄 Mushrooms"},
  {id: "alliums", "type": "Secondary", "label": "🧅 Onions"},
  {id: "nuts", "type": "Secondary", "label": "🌰 Nuts/Seeds"},
  {id: "beans", "type": "Secondary", "label": "🥫 Beans/Peas"},
  {id: "grains", "type": "Secondary", "label": "🌾 Grains"},
  {id: "sweet_veg", "type": "Secondary", "label": "🍠 Sweet Potato/Taro"},
  
  {id: "grilled", "type": "Prep", "label": "🔥 Grilled/BBQ'd"},
  {id: "fried", "type": "Prep", "label": "🍳 Fried/Sauteed"},
  {id: "smoked", "type": "Prep", "label": "🚬 Smoked"},
  {id: "roasted", "type": "Prep", "label": "♨️ Baked/Roasted"},
  {id: "steamed", "type": "Prep", "label": "😤 Steamed"},
  
  {id: "black_pepper", "type": "Spice", "label": "🖤 Black Pepper"},
  {id: "red_pepper", "type": "Spice", "label": "❤️ Red Pepper"},
  {id: "spicy", "type": "Spice", "label": "🌶 Hot Spices"},
  {id: "herbs", "type": "Spice", "label": "🌿 Herbs"},
  {id: "baking_spices", "type": "Spice", "label": "🍪 Cinammon/Clove/Mace"},
  {id: "exotic_spices", "type": "Spice", "label": "😎 Ginger/Saffron/Turmeric/Anice"},
];

const wineTypes = [
  {name: "Bold Red", pairing: [
    {id: "red_meat", "weight": 2},
    {id: "cured_meat", "weight": 1},
    {id: "pork", "weight": 1},
    {id: "grilled", "weight": 2},
    {id: "smoked", "weight": 1},
    {id: "roasted", "weight": 2},
    {id: "pungent_cheese", "weight": 1},
    {id: "hard_cheese", "weight": 2},
    {id: "alliums", "weight": 1},
    {id: "nightshades", "weight": 1},
    {id: "mushrooms", "weight": 1},
    {id: "black_pepper", "weight": 2},
    {id: "red_pepper", "weight": 1},
    {id: "white_starches", "weight": 1},
    {id: "potato", "weight": 1}
  ]},
  {name: "Medium Red", pairing: [
    {id: "red_meat", "weight": 1},
    {id: "cured_meat", "weight": 1},
    {id: "pork", "weight": 2},
    {id: "poultry", "weight": 1},
    {id: "grilled", "weight": 1},
    {id: "smoked", "weight": 2},
    {id: "roasted", "weight": 1},
    {id: "soft_cheese", "weight": 1},
    {id: "pungent_cheese", "weight": 2},
    {id: "hard_cheese", "weight": 1},
    {id: "alliums", "weight": 2},
    {id: "nightshades", "weight": 2},
    {id: "mushrooms", "weight": 2},
    {id: "beans", "weight": 1},
    {id: "black_pepper", "weight": 1},
    {id: "red_pepper", "weight": 2},
    {id: "herbs", "weight": 1},
    {id: "baking_spices", "weight": 1},
    {id: "exotic_spices", "weight": 2},
    {id: "white_starches", "weight": 1},
    {id: "potato", "weight": 1}
  ]},
  {name: "Light Red", pairing: [
    {id: "cured_meat", "weight": 2},
    {id: "poultry", "weight": 2},
    {id: "grilled", "weight": 1},
    {id: "fried", "weight": 2},
    {id: "smoked", "weight": 1},
    {id: "roasted", "weight": 1},
    {id: "soft_cheese", "weight": 2},
    {id: "alliums", "weight": 1},
    {id: "mushrooms", "weight": 2},
    {id: "nuts", "weight": 1},
    {id: "herbs", "weight": 1},
    {id: "exotic_spices", "weight": 1},
    {id: "white_starches", "weight": 1},
    {id: "grains", "weight": 1},
    {id: "potato", "weight": 1}
  ]},
  {name: "Rose", pairing: [
    {id: "cured_meat", "weight": 1},
    {id: "pork", "weight": 1},
    {id: "poultry", "weight": 1},
    {id: "lobster", "weight": 1},
    {id: "fried", "weight": 1},
    {id: "smoked", "weight": 1},
    {id: "roasted", "weight": 1},
    {id: "soft_cheese", "weight": 1},
    {id: "pungent_cheese", "weight": 1},
    {id: "hard_cheese", "weight": 1},
    {id: "alliums", "weight": 1},
    {id: "root_veg", "weight": 2},
    {id: "nightshades", "weight": 1},
    {id: "nuts", "weight": 1},
    {id: "beans", "weight": 1},
    {id: "red_pepper", "weight": 1},
    {id: "herbs", "weight": 1},
    {id: "baking_spices", "weight": 1},
    {id: "exotic_spices", "weight": 1},
    {id: "white_starches", "weight": 1},
    {id: "grains", "weight": 1},
    {id: "sweet_veg", "weight": 1},
    {id: "potato", "weight": 1}
  ]},
  {name: "Rich White", pairing: [
    {id: "poultry", "weight": 2},
    {id: "fish", "weight": 1},
    {id: "lobster", "weight": 2},
    {id: "fried", "weight": 1},
    {id: "steamed", "weight": 1},
    {id: "soft_cheese", "weight": 2},
    {id: "hard_cheese", "weight": 1},
    {id: "alliums", "weight": 1},
    {id: "root_veg", "weight": 1},
    {id: "mushrooms", "weight": 2},
    {id: "nuts", "weight": 1},
    {id: "herbs", "weight": 1},
    {id: "white_starches", "weight": 1},
    {id: "grains", "weight": 1},
    {id: "potato", "weight": 1}
  ]},
  {name: "Light White", pairing: [
    {id: "poultry", "weight": 1},
    {id: "mollusks", "weight": 1},
    {id: "fish", "weight": 2},
    {id: "lobster", "weight": 1},
    {id: "fried", "weight": 1},
    {id: "steamed", "weight": 2},
    {id: "soft_cheese", "weight": 1},
    {id: "pungent_cheese", "weight": 1},
    {id: "alliums", "weight": 1},
    {id: "green_veg", "weight": 2},
    {id: "nuts", "weight": 1},
    {id: "beans", "weight": 2},
    {id: "red_pepper", "weight": 1},
    {id: "spicy", "weight": 1},
    {id: "herbs", "weight": 2},
    {id: "white_starches", "weight": 1},
    {id: "potato", "weight": 1}
  ]},
  {name: "Sparkling", pairing: [
    {id: "cured_meat", "weight": 1},
    {id: "pork", "weight": 1},
    {id: "poultry", "weight": 1},
    {id: "mollusks", "weight": 2},
    {id: "fish", "weight": 1},
    {id: "grilled", "weight": 1},
    {id: "fried", "weight": 1},
    {id: "smoked", "weight": 1},
    {id: "steamed", "weight": 1},
    {id: "soft_cheese", "weight": 1},
    {id: "pungent_cheese", "weight": 1},
    {id: "hard_cheese", "weight": 1},
    {id: "alliums", "weight": 1},
    {id: "green_veg", "weight": 1},
    {id: "nuts", "weight": 1},
    {id: "beans", "weight": 1},
    {id: "red_pepper", "weight": 1},
    {id: "spicy", "weight": 1},
    {id: "exotic_spices", "weight": 1},
    {id: "white_starches", "weight": 1},
    {id: "potato", "weight": 1},
    // {id: "fruits", "weight": 1}
  ]},
  {name: "Sweet White", pairing: [
    {id: "cured_meat", "weight": 2},
    {id: "lobster", "weight": 1},
    {id: "grilled", "weight": 1},
    {id: "roasted", "weight": 1},
    {id: "steamed", "weight": 1},
    {id: "soft_cheese", "weight": 1},
    {id: "pungent_cheese", "weight": 1},
    {id: "alliums", "weight": 1},
    {id: "root_veg", "weight": 1},
    {id: "nightshades", "weight": 1},
    {id: "nuts", "weight": 2},
    {id: "red_pepper", "weight": 1},
    {id: "spicy", "weight": 2},
    {id: "baking_spices", "weight": 1},
    {id: "exotic_spices", "weight": 2},
    {id: "white_starches", "weight": 1},
    {id: "grains", "weight": 2},
    {id: "sweet_veg", "weight": 2},
    {id: "potato", "weight": 1},
    {id: "fruits", "weight": 2},
    {id: "vanilla", "weight": 1}
  ]},
  {name: "Dessert", pairing: [
    {id: "cured_meat", "weight": 1},
    {id: "smoked", "weight": 1},
    {id: "soft_cheese", "weight": 1},
    {id: "pungent_cheese", "weight": 2},
    {id: "baking_spices", "weight": 2},
    {id: "white_starches", "weight": 1},
    {id: "fruits", "weight": 1},
    {id: "vanilla", "weight": 1},
    {id: "chocolate", "weight": 2}
  ]},
];

export default { ingredients, wineTypes };