const ingredients = [
  {name: "Red Meat", "type": "Main"},
  {name: "Cured Meat", "type": "Main"},
  {name: "Pork", "type": "Main"},
  {name: "Poultry", "type": "Main"},
  {name: "Mollusks", "type": "Main"},
  {name: "Fish", "type": "Main"},
  {name: "Lobster & Shellfish", "type": "Main"},
  
  {name: "Soft Cheese & Cream", "type": "Secondary"},
  {name: "Pungent Cheese", "type": "Secondary"},
  {name: "Hard Cheese", "type": "Secondary"},
  {name: "Alliums", "type": "Secondary"},
  {name: "Green Vegetables", "type": "Secondary"},
  {name: "Root Vegetables & Squash", "type": "Secondary"},
  {name: "Nightshades", "type": "Secondary"},
  {name: "Mushrooms", "type": "Secondary"},
  {name: "Nuts & Seeds", "type": "Secondary"},
  {name: "Beans & Peas", "type": "Secondary"},
  {name: "White Starches", "type": "Secondary"},
  {name: "Whole Wheat Grains", "type": "Secondary"},
  {name: "Sweet Starchy Vegetables", "type": "Secondary"},
  {name: "Potato", "type": "Secondary"},
  // {name: "Fruit & Berries", "type": "Secondary"},
  // {name: "Vanilla & Caramel", "type": "Secondary"},
  // {name: "Chocolate & Coffee", "type": "Secondary"},
  
  {name: "Grilled / BBQ", "type": "Prep"},
  {name: "Sauteed / Fried", "type": "Prep"},
  {name: "Smoked", "type": "Prep"},
  {name: "Roasted", "type": "Prep"},
  {name: "Poached / Steamed", "type": "Prep"},
  
  {name: "Black Pepper", "type": "Spice"},
  {name: "Red Pepper", "type": "Spice"},
  {name: "Hot & Spicy", "type": "Spice"},
  {name: "Herbs", "type": "Spice"},
  {name: "Baking Spices", "type": "Spice"},
  {name: "Exotic & Aromatic Spices", "type": "Spice"},
];

const wineTypes = [
  {name: "Bold Red", pairing: [
    {"name": "Red Meat", "weight": 2},
    {"name": "Cured Meat", "weight": 1},
    {"name": "Pork", "weight": 1},
    {"name": "Grilled / BBQ", "weight": 2},
    {"name": "Smoked", "weight": 1},
    {"name": "Roasted", "weight": 2},
    {"name": "Pungent Cheese", "weight": 1},
    {"name": "Hard Cheese", "weight": 2},
    {"name": "Alliums", "weight": 1},
    {"name": "Nightshades", "weight": 1},
    {"name": "Mushrooms", "weight": 1},
    {"name": "Black Pepper", "weight": 2},
    {"name": "Red Pepper", "weight": 1},
    {"name": "White Starches", "weight": 1},
    {"name": "Potato", "weight": 1}
  ]},
  {name: "Medium Red", pairing: [
    {"name": "Red Meat", "weight": 1},
    {"name": "Cured Meat", "weight": 1},
    {"name": "Pork", "weight": 2},
    {"name": "Poultry", "weight": 1},
    {"name": "Grilled / BBQ", "weight": 1},
    {"name": "Smoked", "weight": 2},
    {"name": "Roasted", "weight": 1},
    {"name": "Soft Cheese & Cream", "weight": 1},
    {"name": "Pungent Cheese", "weight": 2},
    {"name": "Hard Cheese", "weight": 1},
    {"name": "Alliums", "weight": 2},
    {"name": "Nightshades", "weight": 2},
    {"name": "Mushrooms", "weight": 2},
    {"name": "Beans & Peas", "weight": 1},
    {"name": "Black Pepper", "weight": 1},
    {"name": "Red Pepper", "weight": 2},
    {"name": "Herbs", "weight": 1},
    {"name": "Baking Spices", "weight": 1},
    {"name": "Exotic & Aromatic Spices", "weight": 2},
    {"name": "White Starches", "weight": 1},
    {"name": "Potato", "weight": 1}
  ]},
  {name: "Light Red", pairing: [
    {"name": "Cured Meat", "weight": 2},
    {"name": "Poultry", "weight": 2},
    {"name": "Grilled / BBQ", "weight": 1},
    {"name": "Sauteed / Fried", "weight": 2},
    {"name": "Smoked", "weight": 1},
    {"name": "Roasted", "weight": 1},
    {"name": "Soft Cheese & Cream", "weight": 2},
    {"name": "Alliums", "weight": 1},
    {"name": "Mushrooms", "weight": 2},
    {"name": "Nuts & Seeds", "weight": 1},
    {"name": "Herbs", "weight": 1},
    {"name": "Exotic & Aromatic Spices", "weight": 1},
    {"name": "White Starches", "weight": 1},
    {"name": "Whole Wheat Grains", "weight": 1},
    {"name": "Potato", "weight": 1}
  ]},
  {name: "Rose", pairing: [
    {"name": "Cured Meat", "weight": 1},
    {"name": "Pork", "weight": 1},
    {"name": "Poultry", "weight": 1},
    {"name": "Lobster & Shellfish", "weight": 1},
    {"name": "Sauteed / Fried", "weight": 1},
    {"name": "Smoked", "weight": 1},
    {"name": "Roasted", "weight": 1},
    {"name": "Soft Cheese & Cream", "weight": 1},
    {"name": "Pungent Cheese", "weight": 1},
    {"name": "Hard Cheese", "weight": 1},
    {"name": "Alliums", "weight": 1},
    {"name": "Root Vegetables & Squash", "weight": 2},
    {"name": "Nightshades", "weight": 1},
    {"name": "Nuts & Seeds", "weight": 1},
    {"name": "Beans & Peas", "weight": 1},
    {"name": "Red Pepper", "weight": 1},
    {"name": "Herbs", "weight": 1},
    {"name": "Baking Spices", "weight": 1},
    {"name": "Exotic & Aromatic Spices", "weight": 1},
    {"name": "White Starches", "weight": 1},
    {"name": "Whole Wheat Grains", "weight": 1},
    {"name": "Sweet Starchy Vegetables", "weight": 1},
    {"name": "Potato", "weight": 1}
  ]},
  {name: "Rich White", pairing: [
    {"name": "Poultry", "weight": 2},
    {"name": "Fish", "weight": 1},
    {"name": "Lobster & Shellfish", "weight": 2},
    {"name": "Sauteed / Fried", "weight": 1},
    {"name": "Poached / Steamed", "weight": 1},
    {"name": "Soft Cheese & Cream", "weight": 2},
    {"name": "Hard Cheese", "weight": 1},
    {"name": "Alliums", "weight": 1},
    {"name": "Root Vegetables & Squash", "weight": 1},
    {"name": "Mushrooms", "weight": 2},
    {"name": "Nuts & Seeds", "weight": 1},
    {"name": "Herbs", "weight": 1},
    {"name": "White Starches", "weight": 1},
    {"name": "Whole Wheat Grains", "weight": 1},
    {"name": "Potato", "weight": 1}
  ]},
  {name: "Light White", pairing: [
    {"name": "Poultry", "weight": 1},
    {"name": "Mollusks", "weight": 1},
    {"name": "Fish", "weight": 2},
    {"name": "Lobster & Shellfish", "weight": 1},
    {"name": "Sauteed / Fried", "weight": 1},
    {"name": "Poached / Steamed", "weight": 2},
    {"name": "Soft Cheese & Cream", "weight": 1},
    {"name": "Pungent Cheese", "weight": 1},
    {"name": "Alliums", "weight": 1},
    {"name": "Green Vegetables", "weight": 2},
    {"name": "Nuts & Seeds", "weight": 1},
    {"name": "Beans & Peas", "weight": 2},
    {"name": "Red Pepper", "weight": 1},
    {"name": "Hot & Spicy", "weight": 1},
    {"name": "Herbs", "weight": 2},
    {"name": "White Starches", "weight": 1},
    {"name": "Potato", "weight": 1}
  ]},
  {name: "Sparkling", pairing: [
    {"name": "Cured Meat", "weight": 1},
    {"name": "Pork", "weight": 1},
    {"name": "Poultry", "weight": 1},
    {"name": "Mollusks", "weight": 2},
    {"name": "Fish", "weight": 1},
    {"name": "Grilled / BBQ", "weight": 1},
    {"name": "Sauteed / Fried", "weight": 1},
    {"name": "Smoked", "weight": 1},
    {"name": "Poached / Steamed", "weight": 1},
    {"name": "Soft Cheese & Cream", "weight": 1},
    {"name": "Pungent Cheese", "weight": 1},
    {"name": "Hard Cheese", "weight": 1},
    {"name": "Alliums", "weight": 1},
    {"name": "Green Vegetables", "weight": 1},
    {"name": "Nuts & Seeds", "weight": 1},
    {"name": "Beans & Peas", "weight": 1},
    {"name": "Red Pepper", "weight": 1},
    {"name": "Hot & Spicy", "weight": 1},
    {"name": "Exotic & Aromatic Spices", "weight": 1},
    {"name": "White Starches", "weight": 1},
    {"name": "Potato", "weight": 1},
    {"name": "Fruit & Berries", "weight": 1}
  ]},
  {name: "Sweet White", pairing: [
    {"name": "Cured Meat", "weight": 2},
    {"name": "Lobster & Shellfish", "weight": 1},
    {"name": "Grilled / BBQ", "weight": 1},
    {"name": "Roasted", "weight": 1},
    {"name": "Poached / Steamed", "weight": 1},
    {"name": "Soft Cheese & Cream", "weight": 1},
    {"name": "Pungent Cheese", "weight": 1},
    {"name": "Alliums", "weight": 1},
    {"name": "Root Vegetables & Squash", "weight": 1},
    {"name": "Nightshades", "weight": 1},
    {"name": "Nuts & Seeds", "weight": 2},
    {"name": "Red Pepper", "weight": 1},
    {"name": "Hot & Spicy", "weight": 2},
    {"name": "Baking Spices", "weight": 1},
    {"name": "Exotic & Aromatic Spices", "weight": 2},
    {"name": "White Starches", "weight": 1},
    {"name": "Whole Wheat Grains", "weight": 2},
    {"name": "Sweet Starchy Vegetables", "weight": 2},
    {"name": "Potato", "weight": 1},
    {"name": "Fruit & Berries", "weight": 2},
    {"name": "Vanilla & Caramel", "weight": 1}
  ]},
  {name: "Dessert", pairing: [
    {"name": "Cured Meat", "weight": 1},
    {"name": "Smoked", "weight": 1},
    {"name": "Soft Cheese & Cream", "weight": 1},
    {"name": "Pungent Cheese", "weight": 2},
    {"name": "Baking Spices", "weight": 2},
    {"name": "White Starches", "weight": 1},
    {"name": "Fruit & Berries", "weight": 1},
    {"name": "Vanilla & Caramel", "weight": 1},
    {"name": "Chocolate & Coffee", "weight": 2}
  ]},
];

export default { ingredients, wineTypes };